# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron:  '0 1 * * *'
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - run: npm install
    - run: NYSE_API_URL='${{ secrets.NYSE_API_URL }}' NASDAQ_API_URL='${{ secrets.NASDAQ_API_URL }}' DATA_API_URL='${{ secrets.DATA_API_URL }}' node index.js
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Gennaro Napolitano
        author_email: stonks@gennaro.me
        message: 'updated on ${{ steps.date.outputs.date }}'
        add: '.'
